### ISSUE TITLE
There is an event handler () => this.clickMe() attached that is not supported by corresponding method in [object HTMLButtonElement]     at Function.eventHub

### ISSUE THREAD

**Issue by logiticks-github** [joergkrause/nyaf#1]
When I try, n-on-Click , there is some errror on button click.

Code

     import { BaseComponent, ComponentData } from '@nyaf/lib';
     import JSX, { CustomElement } from '@nyaf/lib';

     const { dialog } = require('electron')
 
     @CustomElement('app-buttons')
     export class Button Component extends BaseComponent {
      constructor() {
     super();
      };
  
     clickMe() {
      console.log('Button Element Click ');
      }
      protected getData(): ComponentData {
      return {};
      }

      static get observedAttributes() {
   
       return [];
       }
  

  
       render() {
 
        return (
         <>
    
         <div >
      
          <div class="pull-right">
            <button type="button"  n-on-Click={() => this.clickMe()} class="btn btn-outline- 
     secondary">Click</button>
          </div>
          </div>
        </>
         );
        }
     }

![Capture11](https://user-images.githubusercontent.com/14036620/58707279-0d3d4200-83d2-11e9-9628-64e040517a6e.JPG)

**Comment by joergkrause** [comment]
Quick fix is using simply the method name: n-on-Click="clickMe" instead of an expression. 
I'll add a more robust evaluation to next version of lib.

**Comment by logiticks-github** [comment]
Thank you for your quick response, but it's not working, get the same error,

Uncaught Error: [NYAF] There is an event handler clickMe attached that is not supported by corresponding method in [object HTMLButtonElement]
    at Function.eventHub (main.js:173)
    at HTMLDocument.document.addEventListener.e (main.js:173)

**Comment by joergkrause** [comment]
Fixed in 0.0.10. Now the registered components are used to walk up the tree until the handler method has been found.

**Comment by logiticks-github** [comment]
Great! It's working fine. one more doubt, how can I update a variable change in tsx/jsx file? In react we can use setState. In tsx file, a variable value change, then I want to update that in ui also

**Comment by joergkrause** [comment]
In basecomponent is a method setup, which works similar. Technically it's just calling render. So change values and call super.setup(), then it renders again.
