### ISSUE TITLE
executing npx nyaf n throws error

### ISSUE THREAD

**Issue by idseefeld** [joergkrause/nyaf#18]
`npx nyaf n`
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'typedoc/dist/lib/utils'
...

**My environment**

- Windows 10 Pro
- Visual Studio Code 1.54.3
- node version: 14.15.0
- npm version: 6.14.8

**Comment by idseefeld** [comment]
some system clean up and reinstalling fixed this issue. I cannot tell what exactly did the trick:-(

**Comment by joergkrause** [comment]
I removed the reference to "typedoc/dist/lib/utils" in version 0.7.3, which is wrong and not necessary.
